syntax = "proto3";

package exclave.core.transport.internet.hysteria2;
option csharp_namespace = "Exclave.Core.Transport.Internet.Hysteria2";
option go_package = "github.com/exclavenetwork/exclave-core/v5/transport/internet/hysteria2";
option java_package = "com.github.exclavenetwork.exclave.core.transport.internet.hysteria2";
option java_multiple_files = true;

import "common/protoext/extensions.proto";

message Congestion{
  string type = 1;

  uint64 up_mbps = 2;
  uint64 down_mbps = 3;

  string bbrProfile = 4;

  bool disable_loss_compensation = 5;
}

message OBFS {
  string type = 1;
  string password = 2;
  int32 min_packet_size = 3;
  int32 max_packet_size = 4;
}

message Config {
  option (exclave.core.common.protoext.message_opt).type = "transport";
  option (exclave.core.common.protoext.message_opt).short_name = "hysteria2";

  string password = 3;
  Congestion congestion = 4;
  bool ignore_client_bandwidth = 5;
  bool use_udp_extension = 6;
  OBFS obfs = 7;
  repeated string passwords = 8;
  string hop_ports = 9;
  uint64 hop_interval = 10;
  uint64 hop_interval_min = 11;
  uint64 hop_interval_max = 12;
  bool disable_stateless_reset = 13;
  bool omit_max_datagram_frame_size = 1000;
  bool chrome_parrot = 1001;
}
